version: '3.6'
services:
  db-server:
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Samplepassword123
  insurance-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=samplepassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=azure-sql-edge;Database=Insurance;User=sa;Password=Samplepassword123
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./https:/https/:ro
    networks:
      - localdev