version: "3.6"
networks:
  localdev:
    name: localdev

services:
  db-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azure-sql-edge
    networks:
      - localdev
    volumes:
      - sqlvolume:/var/opt/azure-sql-edge      
  insurance-api:
    entrypoint: ["./wait-for.sh", "azure-sql-edge:1433", "-t", "120", "--", "dotnet", "Insurance.Api.dll"]
    build:
      context: .
      dockerfile: src/Insurance.Api/Dockerfile
    image: insurance-api:local
    container_name: insurance-api
    depends_on:
      - db-server
    networks:
      - localdev

volumes:
  sqlvolume: